export { default as Dashboard } from './dashboard'
export { default as NotFound } from './NotFound'
export { default as Login } from './login'
export { default as UserComponent } from './user'
export { default as ForgotPassword } from './forgotPassword'
export { default as ResetPassword } from './resetPassword'